import test from'node:test';import assert from'node:assert/strict';import {chartDOM} from'./helpers/chart-dom.mjs';
const wallet='So11111111111111111111111111111111111111112',sig='2'.repeat(88),mint='3'.repeat(44),quote='6GmAFSYs4gk3FDao5FzzySQpPZaWsa4rUJHacpMpUNgx';
const config={topblastMint:mint,rewardMint:quote,projectId:'blast-stonk-v1',supabaseUrl:'https://test.invalid',supabaseKey:'sb_publishable_test_value',indexVerified:true,marketVerified:true,rewardsActive:false};
const now=Math.floor(Date.now()/1000),stamp=new Date(now*1000).toISOString();
const status={project_id:config.projectId,burned_mint:mint,ember_mint:quote,current_epoch:Math.floor(now/900),current_price_raw:'1000000000000000000000',burned_decimals:6,ember_decimals:9,current_price_time:stamp,indexed_through_time:stamp,updated_at:stamp,mode:'plan',total_airdropped_ember_raw:'0'};
const account={wallet,tracked_burned_raw:'1000000',entry_price_raw:'2000000000000000000000',total_airdropped_ember_raw:'0',position_status:'excluded',updated_at:stamp};
const buy={event_id:sig+':0',signature:sig,wallet,amount_toplast_raw:'1000000',amount_ember_raw:'2000000000',slot:100,occurred_at:stamp};
function fixture(){let accounts=[{...account}],s={...status},buys=[{...buy}];const t=chartDOM({config,fetchImpl:async url=>{const path=new URL(url).pathname;let rows=[];if(path.endsWith('burned_worker_status'))rows=[s];else if(path.endsWith('burned_wallet_accounts'))rows=accounts;else if(path.endsWith('toplast_buys'))rows=buys;else if(path.endsWith('blast_wallet_details'))rows=[{wallet,entry_time:stamp,updated_at:s.updated_at,reward_eligible:false,exclusion_reason:'Sold or sent during this epoch'}];return {ok:true,text:async()=>JSON.stringify(rows)};}});return {...t,setAccount:a=>accounts=[a],setStatus:a=>s=a,setBuys:a=>buys=a};}
const settle=()=>new Promise(r=>setTimeout(r,30));
test('verified buy appears once on tape and chart, and click links wallet inspector',async()=>{const t=fixture();t.boot();await settle();assert.equal(t.document.querySelectorAll('.tape-row').length,1);assert.equal(t.document.querySelectorAll('.buy-dot').length,1);t.document.querySelector('.tape-row button').click();await settle();assert.equal(t.document.getElementById('position-status').textContent,'BLASTED');assert.equal(t.document.getElementById('eligibility').textContent,'EXCLUDED');assert.equal(t.document.querySelectorAll('.buy-dot.selected').length,1);await t.timers.find(x=>x.ms===15000).f();assert.equal(t.document.querySelectorAll('.tape-row').length,1);assert.equal(t.document.querySelectorAll('.buy-dot').length,1);});
test('historical viewport survives new canonical prices; entry updates do not rewrite old buy',async()=>{const t=fixture();t.boot();await settle();const chart=t.charts[0],range={from:now-500,to:now-100};chart.timeScale().setVisibleRange(range);const stamp2=new Date((now+15)*1000).toISOString();t.setStatus({...status,updated_at:stamp2,current_price_time:stamp2,indexed_through_time:stamp2,current_price_raw:'1500000000000000000000'});t.setAccount({...account,updated_at:stamp2,entry_price_raw:'1750000000000000000000'});t.setBuys([buy,buy]);await t.timers.find(x=>x.ms===15000).f();assert.deepEqual(chart.timeScale().getVisibleRange(),range);assert.equal(t.document.querySelectorAll('.tape-row').length,1);assert.match(t.document.querySelector('.buy-dot').title,/Execution 2 STONK/);});
test('switching wallets clears old receipts before the new request resolves',async()=>{const t=fixture();t.boot();await settle();t.document.querySelector('.tape-row button').click();await settle();t.document.getElementById('wallet-rewards').textContent='OLD WALLET RECEIPT';t.document.getElementById('wallet-search').value='11111111111111111111111111111111';t.document.getElementById('wallet-form').dispatchEvent(new t.document.defaultView.Event('submit',{cancelable:true}));assert.doesNotMatch(t.document.getElementById('wallet-rewards').textContent,/OLD WALLET/);await settle();});
