import test from'node:test';import assert from'node:assert/strict';import{readFileSync}from'node:fs';import{runInNewContext}from'node:vm';
const window={};runInNewContext(readFileSync('public/index-data.js','utf8'),{window});const data=window.TopBlastIndex;
test('large atomic amounts retain every digit from PostgREST JSON',()=>{const result=data.parse('{"raw":123456789012345678901234567890,"price":0.25,"note":"123456789012345678901234","slot":446000000}');assert.equal(result.raw,'123456789012345678901234567890');assert.equal(result.note,'123456789012345678901234');assert.equal(result.price,0.25);assert.equal(result.slot,446000000);});
test('fresh sync timestamp cannot hide a stale finalized chain cursor',()=>{const now=Date.now();assert.equal(data.fresh({updated_at:new Date(now).toISOString(),indexed_through_time:new Date(now-181000).toISOString()},now),false);assert.equal(data.fresh({updated_at:new Date(now).toISOString(),indexed_through_time:new Date(now-1000).toISOString()},now),true);});
test('wallet and price snapshots must have the same timestamp',()=>{assert.equal(data.sameSnapshot({updated_at:'2026-09-11T00:00:00Z'},{updated_at:'2026-09-11T00:00:00.000Z'}),true);assert.equal(data.sameSnapshot({updated_at:'2026-09-11T00:00:01Z'},{updated_at:'2026-09-11T00:00:00Z'}),false);assert.equal(data.sameSnapshot({},{}),false);});
test('historical buys outside the plotted interval cannot appear as new chart markers',()=>{const start=Date.parse('2026-09-11T21:00:00Z'),end=start+60000;const buys=[{id:'old',occurred_at:'2026-09-11T18:00:00Z'},{id:'start',occurred_at:new Date(start).toISOString()},{id:'end',occurred_at:new Date(end).toISOString()},{id:'future',occurred_at:new Date(end+1).toISOString()},{id:'invalid',occurred_at:'bad'}];assert.equal(data.buysInWindow(buys,start,end).map(b=>b.id).join(','),'start,end');});
test('relative activity time uses compact honest units',()=>{const now=Date.parse('2026-09-11T21:00:00Z');assert.equal(data.relativeTime('2026-09-11T20:57:01Z',now),'2m ago');assert.equal(data.relativeTime('2026-09-11T19:00:00Z',now),'2h ago');assert.equal(data.relativeTime('bad',now),'time unavailable');});
test('crossing events require an observed canonical safe and blasted transition',()=>{assert.equal(data.crossing({position_status:'safe'},{position_status:'blasted'}),'entered');assert.equal(data.crossing({position_status:'blasted'},{position_status:'safe'}),'left');for(const pair of [[null,{position_status:'blasted'}],[{position_status:'excluded'},{position_status:'blasted'}],[{position_status:'blasted'},{position_status:'excluded'}],[{position_status:'safe'},{position_status:'safe'}]])assert.equal(data.crossing(...pair),null);});
test('activity UI keeps verified buy units and refresh cadence explicit',()=>{const source=readFileSync('public/app.js','utf8');assert.match(source,/Bought \$\{amount\} \$EMBER worth/);assert.match(source,/loadActivity\(\); \}, 60000/);assert.match(source,/loadProtocol\(\); \}, 15000/);assert.match(source,/amount: item\.amount_ember_raw/);assert.doesNotMatch(source,/Bought \$\{amount\} SOL/);});
