import {parseHTML} from 'linkedom';import {readFileSync} from 'node:fs';import {runInNewContext} from 'node:vm';
export function chartDOM({config={},fetchImpl=async()=>{throw Error('Unexpected network')}}={}){
 const {window}=parseHTML(readFileSync('public/index.html','utf8')),document=window.document,charts=[],timers=[];
 const matchMedia=()=>({matches:true,addEventListener(){}});const scale=()=>({applyOptions(){}});
 const L={LineSeries:'line',CandlestickSeries:'candle',HistogramSeries:'volume',CrosshairMode:{Normal:0},createChart(){let range=null,listener=null;const all=[];const time={width:()=>700,getVisibleRange:()=>range,setVisibleRange:r=>{range={...r};listener?.(range)},subscribeVisibleTimeRangeChange:f=>listener=f,fitContent(){const rows=all.flatMap(s=>s.data);if(rows.length)range={from:Math.min(...rows.map(r=>r.time)),to:Math.max(...rows.map(r=>r.time))};},scrollToRealTime(){const rows=all.flatMap(s=>s.data);if(rows.length){const last=Math.max(...rows.map(r=>r.time)),span=range?range.to-range.from:300;range={from:last-span,to:last};}},timeToCoordinate:t=>range?Math.max(5,Math.min(690,(t-range.from)/Math.max(1,range.to-range.from)*690)):null};const chart={all,timeScale:()=>time,priceScale:scale,subscribeCrosshairMove(){},addSeries(type){const s={type,data:[],updates:0,options:{},applyOptions:o=>Object.assign(s.options,o),setData:rows=>{s.data=rows.map(r=>({...r}))},update:r=>{s.updates++;const i=s.data.findIndex(x=>x.time===r.time);if(i>=0)s.data[i]={...r};else s.data.push({...r});},priceScale:scale,priceToCoordinate:p=>p===null?null:Math.max(20,Math.min(380,200-p*10)),createPriceLine:o=>o,removePriceLine(){}};all.push(s);return s;}};charts.push(chart);return chart;}};
 for(const dialog of document.querySelectorAll('dialog')){dialog.showModal=()=>{dialog.open=true};dialog.close=()=>{dialog.open=false};}
 Object.defineProperty(document.getElementById('market-chart'),'clientHeight',{value:460});
 const fakeWindow={...window,LightweightCharts:L,__BLAST_PUBLIC_CONFIG__:config,matchMedia,setInterval:(f,ms)=>timers.push({f,ms}),setTimeout,clearTimeout,addEventListener(){}};
 const context={window:fakeWindow,document,console,URL,URLSearchParams,AbortSignal,Date,Intl,setTimeout,clearTimeout,fetch:fetchImpl,matchMedia,ResizeObserver:class{observe(){}},requestAnimationFrame:f=>f()};
 for(const file of ['index-data.js','broadcast-data.js','market-client.js','chart-interaction.js','blast-map.js'])runInNewContext(readFileSync('public/'+file,'utf8'),context,{filename:file});
 return {window:fakeWindow,document,charts,timers,context,boot(){runInNewContext(readFileSync('public/broadcast.js','utf8'),context,{filename:'broadcast.js'})}};
}
