import React,{useMemo,useState} from 'react';
import {isAddress} from 'ethers';
import {runtime,explorerLink} from './config.mjs';
import {TopblastChart} from './TopblastChart.jsx';
import {TopblastLogo} from './TopblastLogo.jsx';
import {lookupWallet,useMarketData} from './useMarketData.mjs';

const dash='—';
const short=(value='')=>value?`${value.slice(0,6)}…${value.slice(-4)}`:dash;
const fmt=(value,digits=4)=>value==null?dash:Number(value).toLocaleString(undefined,{maximumFractionDigits:digits});
const ago=value=>{if(!value)return 'NEVER';const sec=Math.max(0,Math.floor((Date.now()-new Date(value).getTime())/1000));return sec<60?`${sec}S AGO`:sec<3600?`${Math.floor(sec/60)}M AGO`:`${Math.floor(sec/3600)}H AGO`};
const statusCopy={awaiting_configuration:'PRELAUNCH',connecting:'SYNCING',live:'LIVE',delayed:'DELAYED',reconnecting:'SYNCING',paused:'PAUSED'};

function Metric({label,value,accent=false}){return <div className="metric"><span>{label}</span><strong className={accent?'accent':''}>{value??dash}</strong></div>}

function WalletInspector({wallet,onClose,onFocus}){
  if(!wallet)return <aside className="inspector empty-panel" id="wallet-result"><div className="empty-signal" aria-hidden="true"><i/><i/><i/></div><span className="panel-label">WALLET LOOKUP</span><h2>SEARCH A WALLET<br/>TO FIND ITS ENTRY.</h2><p>Verified entry, live return and Blast Zone status come directly from the finalized index.</p></aside>;
  const blasted=wallet.status==='blasted';
  const performance=wallet.returnPercent==null?dash:`${wallet.returnPercent>0?'+':''}${fmt(wallet.returnPercent,2)}% ${blasted?'BELOW':'ABOVE'} ENTRY`;
  return <aside className="inspector" id="wallet-result"><div className="panel-head"><span className="panel-label">YOUR TOPBLAST</span><button onClick={onClose} aria-label="Close wallet">×</button></div><div className="wallet-id">{short(wallet.wallet)}</div><div className={`wallet-state ${blasted?'blasted':'clear'}`}><span>STATUS</span><strong>{blasted?"YOU'RE BLASTED":"YOU'RE CLEAR"}</strong><small>{performance}</small></div><div className="inspector-grid"><Metric label="TRACKED TOPBLAST" value={fmt(wallet.trackedBalance,2)}/><Metric label="WEIGHTED ENTRY" value={wallet.averageEntry==null?dash:`${fmt(wallet.averageEntry,8)} QQQ`}/><Metric label="CURRENT PRICE" value={wallet.currentPrice==null?dash:`${fmt(wallet.currentPrice,8)} QQQ`}/><Metric label="POSITION" value={wallet.returnPercent==null?dash:`${wallet.returnPercent>0?'+':''}${fmt(wallet.returnPercent,2)}%`}/><Metric label="FIRST VERIFIED BUY" value={wallet.firstBuyAt?new Date(Number(wallet.firstBuyAt)*1000).toLocaleDateString():dash}/><Metric label="LATEST VERIFIED BUY" value={wallet.lastBuyAt?new Date(Number(wallet.lastBuyAt)*1000).toLocaleDateString():dash}/><Metric label="EPOCH STATUS" value={wallet.eligible?'ELIGIBLE':wallet.exclusionReason?.replaceAll('_',' ').toUpperCase()||'NOT ELIGIBLE'} accent={wallet.eligible}/><Metric label="QQQ RECEIVED" value={fmt(wallet.rewardsReceived,4)}/></div><button className="focus-chart" onClick={onFocus}>FOCUS ON CHART</button></aside>;
}

function StatusControl({market,error}){
  const label=statusCopy[market.status]||String(market.status||'connecting').toUpperCase();
  return <details className={`status-control ${market.status}`}><summary><i/>{label}</summary><div><b>MARKET FEED</b><span>{error||market.status==='live'?'Finalized Pons market data.':'Awaiting verified production configuration.'}</span><small>Last finalized update: {ago(market.lastUpdated)}</small></div></details>;
}

export function App(){
  const [interval,setIntervalValue]=useState('1m'),[query,setQuery]=useState(''),[selected,setSelected]=useState(null),[lookupError,setLookupError]=useState(''),[looking,setLooking]=useState(false),[chartFocus,setChartFocus]=useState(0);
  const {market,error}=useMarketData(interval),events=market.events||[];
  const countdown=useMemo(()=>market.epoch?.nextAt?Math.max(0,Math.floor((new Date(market.epoch.nextAt)-Date.now())/1000)):null,[market.epoch?.nextAt,market.lastUpdated]);
  const verifiedFeeBps=market.config?.feeBps==null?null:Number(market.config.feeBps)+Number(market.config.creatorTaxBps||0),feeLabel=verifiedFeeBps==null?'1.5%':`${fmt(verifiedFeeBps/100,2)}%`;
  const liveToken=market.config?.token||runtime.tokenAddress,buyUrl=liveToken?`https://www.ponsfamily.com/launchpad/${liveToken}`:runtime.buyUrl;
  async function loadWallet(wallet){setLookupError('');setLooking(true);try{const result=await lookupWallet(wallet);setSelected(result);return result}catch(reason){setSelected(null);setLookupError(reason.message==='Failed to fetch'?(runtime.tokenAddress?'Wallet lookup is temporarily unavailable.':'No verified Topblast entry found. Market is prelaunch.'):reason.message)}finally{setLooking(false)}}
  async function search(event){event.preventDefault();if(!isAddress(query)){setLookupError('Enter a valid Robinhood Chain address.');return}const result=await loadWallet(query);if(result)document.querySelector('#wallet-result')?.scrollIntoView({behavior:'smooth',block:'center'})}
  const selectWallet=async wallet=>{setQuery(wallet);const result=await loadWallet(wallet);if(result)setChartFocus(value=>value+1)};
  const focusChart=()=>{setChartFocus(value=>value+1);document.querySelector('#live-chart')?.scrollIntoView({behavior:'smooth',block:'center'})};
  const blastedCount=market.totals.walletsInZone,trackedCount=market.totals.trackedPositions;
  return <div className="app">
    <header><a className="logo-link" href="#top" aria-label="Topblast home"><TopblastLogo/></a><nav className="desktop-nav"><a href="#live-chart">LIVE CHART</a><a href="#blast-zone">BLAST ZONE</a><a href="#mechanic">HOW IT WORKS</a><a href="#tape">TOPBLAST TAPE</a></nav><StatusControl market={market} error={error}/><button className="search-action" onClick={()=>document.querySelector('#wallet-search')?.focus()} aria-label="Search wallet">⌕</button>{buyUrl?<a className="buy" href={buyUrl}>BUY TOPBLAST</a>:<span className="buy disabled" aria-disabled="true">LAUNCH PENDING</span>}</header>
    <main id="top">
      <section className="market-heading"><div className="hero-copy"><span className="kicker">ROBINHOOD CHAIN · PONS V2</span><h1>BUY THE TOP.<br/><em>WATCH IT BLAST.</em></h1><p>Every verified buy creates a public entry. If the market falls below it, that wallet enters the Blast Zone.</p><div className="hero-actions"><a className="primary-action" href="#live-chart">VIEW LIVE CHART</a><a className="secondary-action" href="#wallet-search">FIND MY ENTRY</a></div><div className="hero-specs"><span><b>PAIR</b> TOPBLAST / QQQ</span><span><b>FEE</b> {feeLabel}</span><span><b>STATUS</b> {statusCopy[market.status]||'SYNCING'}</span></div></div><div className="hero-visual"><img src="/topblast-robinhood-banner.jpg" alt="Topblast on Robinhood"/><div className="headline-price"><span>TOPBLAST / QQQ</span><strong>{market.price==null?dash:fmt(market.price,8)}</strong><small className={(market.change24h||0)>=0?'positive':'negative'}>{market.change24h==null?'LAUNCH PENDING':`${market.change24h>0?'+':''}${fmt(market.change24h,2)}% · 24H`}</small></div></div></section>
      <section className="wallet-command" aria-label="Wallet search"><div><span className="panel-label">FIND MY ENTRY</span><strong>WHERE DID YOU BUY THE TOP?</strong></div><form className="wallet-search" onSubmit={search}><label className="sr-only" htmlFor="wallet-search">Search your wallet</label><input id="wallet-search" value={query} onChange={event=>setQuery(event.target.value)} placeholder="SEARCH YOUR WALLET"/><button>{looking?'SEARCHING…':'FIND MY BLAST'}</button></form>{lookupError&&<p className="lookup-error" role="status">{lookupError.toUpperCase()}</p>}</section>
      <section className="workspace" id="live-chart"><div className="chart-column"><TopblastChart candles={market.candles} buys={market.buys} selectedPosition={selected} onSelectWallet={selectWallet} interval={interval} onInterval={setIntervalValue} focusSignal={chartFocus}/><div className="market-strip"><Metric label="LIVE PRICE" value={market.price==null?dash:`${fmt(market.price,8)} QQQ`}/><Metric label="WALLETS BLASTED" value={blastedCount==null?dash:`${blastedCount} / ${trackedCount??dash}`}/><Metric label="TRACKED POSITIONS" value={trackedCount}/><Metric label="NEXT EPOCH" value={countdown==null?'PENDING':`${String(Math.floor(countdown/60)).padStart(2,'0')}:${String(countdown%60).padStart(2,'0')}`}/></div></div><WalletInspector wallet={selected} onClose={()=>setSelected(null)} onFocus={focusChart}/></section>
      <section className="blast-summary" id="blast-zone"><div className="blast-line"><img src="/topblast-mark-512.png" alt=""/><i/></div><div><span className="panel-label">BLAST ZONE</span><h2>{blastedCount==null?'AWAITING THE MARKET':blastedCount===0?'NO WALLETS BLASTED':'THE TOP IS BLASTING'}</h2><p>Every wallet has its own verified entry. Below that line, it is blasted. Above it, it is clear.</p></div><strong>{blastedCount==null?dash:blastedCount}<small> / {trackedCount??dash}</small></strong></section>
      <section className="lower-grid" id="tape"><div className="feed panel"><div className="section-head"><div><span className="panel-label">FINALIZED ACTIVITY</span><h2>TOPBLAST TAPE</h2></div><small>LAST VERIFIED {ago(market.lastUpdated)}</small></div>{events.length?<div className="event-list">{events.slice(0,12).map(item=>{const blasted=item.currentStatus==='blasted'||item.type==='entered_zone';return <a key={item.id} className={`event ${blasted?'blasted':'clear'}`} href={explorerLink('tx',item.transactionHash)} target="_blank" rel="noreferrer"><span className={`event-dot ${item.type}`}/><b>{short(item.wallet)}</b><strong>{String(item.label||item.type).toUpperCase()}</strong><span>{item.amountLabel||''}</span><time>{ago(item.timestamp)}</time></a>})}</div>:<div className="empty-state tape-empty"><div className="tape-pulse"/><strong>THE FIRST VERIFIED TOPBLAST WILL APPEAR HERE</strong><span>No simulated activity. The tape starts with a finalized Pons trade.</span></div>}</div><div className="leaderboard panel"><div className="section-head"><div><span className="panel-label">BLAST ZONE</span><h2>TOP BLASTERS</h2></div><small>QQQ BASIS</small></div><div className="table-head"><span>#</span><span>WALLET</span><span>ENTRY</span><span>RETURN</span></div>{market.leaderboard?.length?market.leaderboard.slice(0,10).map((row,index)=><button className="leader-row" key={row.wallet} onClick={()=>selectWallet(row.wallet)}><span>{String(index+1).padStart(2,'0')}</span><b>{short(row.wallet)}</b><span>{fmt(row.averageEntry,7)}</span><strong>{fmt(row.returnPercent,2)}%</strong></button>):<div className="empty-state compact"><div className="empty-signal" aria-hidden="true"><i/><i/><i/></div><strong>NO WALLETS IN THE BLAST ZONE</strong><span>Only verified underwater positions appear here.</span></div>}</div></section>
      <section className="mechanic" id="mechanic"><span className="panel-label">THE MECHANIC</span><h2>ENTRY IS PERSONAL.<br/>THE MARKET IS SHARED.</h2><div className="mechanic-diagram" aria-label="Buy, set entry, price falls, blasted"><span>BUY</span><i/><span>ENTRY LINE</span><i/><span>PRICE FALLS</span><i className="danger"/><span className="danger">BLASTED</span></div><div className="steps"><article><b>01</b><h3>BUY</h3><p>A verified Pons trade creates your weighted TOPBLAST entry.</p></article><article><b>02</b><h3>TRACK</h3><p>Your entry stays visible against the finalized market price.</p></article><article><b>03</b><h3>GET BLASTED</h3><p>Below your entry, your wallet enters the Blast Zone.</p></article><article><b>04</b><h3>RECOVER</h3><p>Move back above your entry and your wallet returns to clear.</p></article></div></section>
      <section className="rules"><div><span className="panel-label">LEDGER RULES</span><h2>THE ENTRY<br/>HAS TO BE REAL.</h2></div><div className="rule-list"><p><b>VERIFIED BUY</b><span>Creates tracked basis</span><em>COUNTS</em></p><p><b>ADDITIONAL BUY</b><span>Updates weighted entry</span><em>UPDATES</em></p><p><b>INCOMING TRANSFER</b><span>Creates no basis</span><em>NO ENTRY</em></p><p><b>SELL OR SEND</b><span>Excludes current epoch</span><em>EXCLUDED</em></p></div></section>
    </main>
    <div className="mobile-actions"><a href="#wallet-search">FIND MY BLAST</a>{buyUrl?<a className="hot" href={buyUrl}>BUY TOPBLAST</a>:<span>LAUNCH PENDING</span>}</div>
    <footer><TopblastLogo compact/><span>TOPBLAST / QQQ · PONS V2 · {feeLabel} FEE</span><nav>{liveToken&&<a href={explorerLink('token',liveToken)}>CONTRACT</a>}{runtime.xUrl&&<a href={runtime.xUrl} target="_blank" rel="noreferrer">X</a>}<a href="https://docs.ponsfamily.com/v2" target="_blank" rel="noreferrer">PONS V2</a><a href="https://robinhoodchain.blockscout.com" target="_blank" rel="noreferrer">EXPLORER</a></nav></footer>
  </div>;
}
