import React,{useMemo,useState} from 'react';
import {isAddress} from 'ethers';
import {runtime,explorerLink} from './config.mjs';
import {TopblastChart} from './TopblastChart.jsx';
import {TopblastLogo} from './TopblastLogo.jsx';
import {lookupWallet,useMarketData} from './useMarketData.mjs';

const dash='—';
const short=(value='')=>value?`${value.slice(0,6)}…${value.slice(-4)}`:dash;
const fmt=(value,digits=4)=>value==null?dash:Number(value).toLocaleString(undefined,{maximumFractionDigits:digits});
const ago=value=>{if(!value)return 'NEVER';const sec=Math.max(0,Math.floor((Date.now()-new Date(value).getTime())/1000));return sec<60?`${sec}S AGO`:sec<3600?`${Math.floor(sec/60)}M AGO`:`${Math.floor(sec/3600)}H AGO`};
const statusCopy={awaiting_configuration:'AWAITING MARKET',connecting:'CONNECTING',live:'LIVE',delayed:'DELAYED',reconnecting:'RECONNECTING',paused:'PAUSED'};

function Metric({label,value,accent=false}){return <div className="metric"><span>{label}</span><strong className={accent?'accent':''}>{value??dash}</strong></div>}

function WalletInspector({wallet,onClose}){
  if(!wallet)return <aside className="inspector empty-panel"><span className="panel-label">SELECTED WALLET</span><h2>Find your blast.</h2><p>Search an address or select a real buy marker. Entry and eligibility come from the finalized index.</p></aside>;
  const blasted=wallet.status==='blasted';
  return <aside className="inspector"><div className="panel-head"><span className="panel-label">SELECTED WALLET</span><button onClick={onClose} aria-label="Close wallet">×</button></div><div className="wallet-id">{short(wallet.wallet)}</div><div className={`wallet-state ${blasted?'blasted':'clear'}`}><span>STATUS</span><strong>{blasted?'BLASTED':'CLEAR'}</strong><small>{wallet.eligible?'ELIGIBLE THIS EPOCH':wallet.exclusionReason?.replaceAll('_',' ').toUpperCase()||'NOT ELIGIBLE'}</small></div><div className="inspector-grid"><Metric label="TRACKED TOPBLAST" value={fmt(wallet.trackedBalance,2)}/><Metric label="AVERAGE ENTRY" value={wallet.averageEntry==null?dash:`${fmt(wallet.averageEntry,8)} QQQ`}/><Metric label="CURRENT PRICE" value={wallet.currentPrice==null?dash:`${fmt(wallet.currentPrice,8)} QQQ`}/><Metric label="POSITION" value={wallet.returnPercent==null?dash:`${wallet.returnPercent>0?'+':''}${fmt(wallet.returnPercent,2)}%`}/><Metric label="BLAST DEPTH" value={wallet.blastDepth==null?dash:`${fmt(wallet.blastDepth,2)}%`} accent={blasted}/><Metric label="QQQ RECEIVED" value={fmt(wallet.rewardsReceived,4)}/></div></aside>;
}

export function App(){
  const [interval,setIntervalValue]=useState('1m'),[query,setQuery]=useState(''),[selected,setSelected]=useState(null),[lookupError,setLookupError]=useState(''),[looking,setLooking]=useState(false);
  const {market,error}=useMarketData(interval);
  const events=market.events||[];
  const countdown=useMemo(()=>market.epoch?.nextAt?Math.max(0,Math.floor((new Date(market.epoch.nextAt)-Date.now())/1000)):null,[market.epoch?.nextAt,market.lastUpdated]);
  async function search(event){event.preventDefault();setLookupError('');if(!isAddress(query)){setLookupError('Enter a valid Robinhood Chain address.');return}setLooking(true);try{setSelected(await lookupWallet(query))}catch(reason){setSelected(null);setLookupError(reason.message)}finally{setLooking(false)}}
  const liveToken=market.config?.token||runtime.tokenAddress,buyUrl=liveToken?`https://www.ponsfamily.com/launchpad/${liveToken}`:runtime.buyUrl;
  return <div className="app">
    <header><TopblastLogo/><div className="pair"><i/><span>TOPBLAST / QQQ</span><b>{statusCopy[market.status]||String(market.status).toUpperCase()}</b></div><form className="wallet-search" onSubmit={search}><label htmlFor="wallet">WALLET</label><input id="wallet" value={query} onChange={e=>setQuery(e.target.value)} placeholder="0x…"/><button>{looking?'…':'SEARCH'}</button></form>{runtime.xUrl&&<a className="social-link" href={runtime.xUrl} target="_blank" rel="noreferrer" aria-label="Topblast on X">X</a>}{buyUrl?<a className="buy" href={buyUrl}>BUY TOPBLAST</a>:<span className="buy disabled">BUY AFTER LAUNCH</span>}</header>
    <main>
      <section className="market-heading"><div><span className="kicker">ROBINHOOD CHAIN · PONS V2</span><h1>BUY THE TOP.<br/><em>WATCH IT BLAST.</em></h1><p>Every verified buy sets an entry. Drop below it and the position enters its own Blast Zone.</p></div><div className="headline-price"><span>TOPBLAST / QQQ</span><strong>{market.price==null?dash:fmt(market.price,8)}</strong><small className={(market.change24h||0)>=0?'positive':'negative'}>{market.change24h==null?'AWAITING FIRST TRADE':`${market.change24h>0?'+':''}${fmt(market.change24h,2)}% · 24H`}</small></div></section>
      {(error||lookupError)&&<div className="notice" role="status">{lookupError||'Live index reconnecting. Last verified data remains visible.'}</div>}
      <section className="workspace"><div className="chart-column"><TopblastChart candles={market.candles} buys={market.buys} selectedPosition={selected} onSelectWallet={async wallet=>{setQuery(wallet);setLookupError('');try{setSelected(await lookupWallet(wallet))}catch(reason){setLookupError(reason.message)}}} interval={interval} onInterval={setIntervalValue}/><div className="market-strip"><Metric label="MARKET CAP" value={market.marketCap==null?dash:`${fmt(market.marketCap,2)} QQQ`}/><Metric label="WALLETS BLASTED" value={market.totals.walletsInZone}/><Metric label="TRACKED POSITIONS" value={market.totals.trackedPositions}/><Metric label="NEXT EPOCH" value={countdown==null?'EACH EPOCH':`${String(Math.floor(countdown/60)).padStart(2,'0')}:${String(countdown%60).padStart(2,'0')}`}/></div></div><WalletInspector wallet={selected} onClose={()=>setSelected(null)}/></section>
      <section className="lower-grid"><div className="feed panel"><div className="section-head"><div><span className="panel-label">LIVE LEDGER</span><h2>TOPBLAST TAPE</h2></div><small>LAST VERIFIED {ago(market.lastUpdated)}</small></div>{events.length?<div className="event-list">{events.slice(0,12).map(item=><a key={item.id} className="event" href={explorerLink('tx',item.transactionHash)} target="_blank" rel="noreferrer"><span className={`event-dot ${item.type}`}/><b>{short(item.wallet)}</b><strong>{String(item.label||item.type).toUpperCase()}</strong><span>{item.amountLabel||''}</span><time>{ago(item.timestamp)}</time></a>)}</div>:<div className="empty-state"><strong>WAITING FOR THE FIRST TOPBLAST</strong><span>Verified trades will appear here once the production market is configured.</span></div>}</div><div className="leaderboard panel"><div className="section-head"><div><span className="panel-label">LIVE POSITIONS</span><h2>TOP BLASTERS</h2></div><small>QQQ BASIS</small></div><div className="table-head"><span>#</span><span>WALLET</span><span>ENTRY</span><span>RETURN</span></div>{market.leaderboard?.length?market.leaderboard.slice(0,10).map((row,index)=><button className="leader-row" key={row.wallet} onClick={()=>setSelected(row)}><span>{String(index+1).padStart(2,'0')}</span><b>{short(row.wallet)}</b><span>{fmt(row.averageEntry,7)}</span><strong>{fmt(row.returnPercent,2)}%</strong></button>):<div className="empty-state compact"><strong>NO WALLETS IN THE BLAST ZONE</strong><span>Nothing is shown until finalized data proves it.</span></div>}</div></section>
      <section className="mechanic"><span className="panel-label">THE MECHANIC</span><h2>ENTRY IS PERSONAL.<br/>THE MARKET IS SHARED.</h2><div className="steps"><article><b>01</b><h3>BUY</h3><p>A verified Pons trade creates your QQQ-denominated weighted entry.</p></article><article><b>02</b><h3>GET BLASTED</h3><p>Current price below your entry means your position is underwater.</p></article><article><b>03</b><h3>QUALIFY</h3><p>Underwater wallets that did not sell or send can enter the epoch snapshot.</p></article></div></section>
      <section className="rules"><div><span className="panel-label">LEDGER RULES</span><h2>THE ENTRY<br/>HAS TO BE REAL.</h2></div><div className="rule-list"><p><b>VERIFIED BUY</b><span>Creates tracked basis</span><em>COUNTS</em></p><p><b>ADDITIONAL BUY</b><span>Updates weighted entry</span><em>UPDATES</em></p><p><b>INCOMING TRANSFER</b><span>Creates no basis</span><em>NO ENTRY</em></p><p><b>SELL OR SEND</b><span>Excludes current epoch</span><em>EXCLUDED</em></p></div></section>
    </main>
    <footer><TopblastLogo compact/><span>TOPBLAST / QQQ · ROBINHOOD CHAIN</span><nav>{liveToken&&<a href={explorerLink('token',liveToken)}>CONTRACT</a>}{runtime.xUrl&&<a href={runtime.xUrl} target="_blank" rel="noreferrer">X</a>}<a href="https://docs.ponsfamily.com/v2" target="_blank" rel="noreferrer">PONS V2</a><a href="https://robinhoodchain.blockscout.com" target="_blank" rel="noreferrer">EXPLORER</a></nav></footer>
  </div>;
}
